### ISSUE TITLE
Custom Analyzation needs more explanation.

### ISSUE THREAD

**Issue by BenjaminKim** [wvanbergen/request-log-analyzer#147]
I read this documentation to write my own parser.
https://github.com/wvanbergen/request-log-analyzer/wiki/Creating-your-own-file-format-definition

But when I tryed to run it, an error occurs.

``` bash
 $ request-log-analyzer log/production.log -f lib/my_format.rb
Request-log-analyzer, by Willem van Bergen and Bart ten Brinke - version 1.12.9
Website: http://railsdoctors.com

/usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': /Users/benjamin/workspace/maldive_webapp/lib/my_format.rb:10: syntax error, unexpected ... (SyntaxError)
/Users/benjamin/workspace/maldive_webapp/lib/my_format.rb:16: syntax error, unexpected end-of-input, expecting keyword_end
    from /usr/local/Cellar/ruby/2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Users/benjamin/.rvm/gems/ruby-2.0.0-p247/gems/request-log-analyzer-1.12.9/lib/request_log_analyzer/file_format.rb:41:in `load'
    from /Users/benjamin/.rvm/gems/ruby-2.0.0-p247/gems/request-log-analyzer-1.12.9/lib/request_log_analyzer/controller.rb:182:in `build'
    from /Users/benjamin/.rvm/gems/ruby-2.0.0-p247/gems/request-log-analyzer-1.12.9/lib/request_log_analyzer/controller.rb:92:in `build_from_arguments'
    from /Users/benjamin/.rvm/gems/ruby-2.0.0-p247/gems/request-log-analyzer-1.12.9/bin/request-log-analyzer:129:in `<top (required)>'
    from /Users/benjamin/.rvm/gems/ruby-2.0.0-p247/bin/request-log-analyzer:23:in `load'
    from /Users/benjamin/.rvm/gems/ruby-2.0.0-p247/bin/request-log-analyzer:23:in `<main>'
```

What module or class should I `require`?

This is my formatter. Because I'm trying to make it runs, I didn't implement much yet.

``` ruby
class MyFormat < RequestLogAnalyzer::FileFormat::Base
  # Define line types
  line_definition :my_line_type do |line|
    line.header = "Header"
    line.regexp = /.*REQUEST(.+)/
    line.captures << { :name => :looks_like, :type => :string }
    line.footer = "Footer"
  end

  line_definition :another_line_type do |line| ...

  # define the summary report
  report do |analyze|
    analyze.frequency :looks_like, :title => "Top 20 of looks like phrases", :amount=> 20
  end
end
```

This `issue page` is not a proper place to ask, however, in order to rescue other people who face to same problem with me, I issue it.

**Comment by BenjaminKim** [comment]
OMG. I re-read my code. Sorry.

**Comment by barttenbrinke** [comment]
So did you get everything working ok :)?

**Comment by BenjaminKim** [comment]
@barttenbrinke Yes. I did. :) Work well
