### ISSUE TITLE
undefined method `to_d' 

### ISSUE THREAD

**Issue by willbryant** [wvanbergen/request-log-analyzer#166]
Getting this with version 1.13.0 on both 2.1.3 and 2.0.0-p576:

```
/Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/request.rb:40:in `eval': undefined method `to_d' for "4.27":String (NoMethodError)
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/request.rb:40:in `eval'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/request.rb:40:in `convert_eval'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/request.rb:20:in `convert_value'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/line_definition.rb:122:in `block in convert_captured_values'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/line_definition.rb:119:in `each'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/line_definition.rb:119:in `each_with_index'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/line_definition.rb:119:in `convert_captured_values'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/request.rb:115:in `add_parsed_line'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/request.rb:146:in `<<'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/source/log_parser.rb:315:in `update_current_request'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/source/log_parser.rb:230:in `parse_line'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/source/log_parser.rb:187:in `parse_io_19'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/source/log_parser.rb:156:in `parse_stream'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/source/log_parser.rb:77:in `each_request'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/lib/request_log_analyzer/controller.rb:335:in `run!'
    from /Users/will/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/request-log-analyzer-1.13.0/bin/request-log-analyzer:129:in `<top (required)>'
    from /Users/will/.rbenv/versions/2.1.3/bin/request-log-analyzer:23:in `load'
    from /Users/will/.rbenv/versions/2.1.3/bin/request-log-analyzer:23:in `<main>'
```

I think to_d is an activesupport extension.  Use BigDecimal(...) instead?

**Comment by wvanbergen** [comment]
It looks like this is part of the file format definition you are using for your file. What kind of file is it? 

In the request-log-analyzer source code, not in the file formats we include, we never call `.to_d` ourselves. Are you using a custom file format?

**Comment by willbryant** [comment]
It's a syslog from rsyslog.  I haven't told request-log-analyzer to use a specific format, does it automatically try to find one?

**Comment by wvanbergen** [comment]
If you don't specify one, it will try to detect one.

What version of request-log-analyzer are you using?

**Comment by willbryant** [comment]
I tried both 1.12.0 and 1.13.0.  Is there a way I can tell what format definition it has used?

**Comment by wvanbergen** [comment]
Can you post a snippet of your log file?

**Comment by willbryant** [comment]
Ours looks like this:

```
2014-10-08T10:05:03+13:00 server-here-1 user.info<14> ruby[1427]: Started GET "/unit_balance" for 203.171.53.66 at 2014-10-08 10:05:03 +1300
2014-10-08T10:05:03+13:00 server-here-1 user.info<14> ruby[1427]: Processing by UnitBalanceController#index as HTML
2014-10-08T10:05:03+13:00 server-here-1 user.info<14> ruby[1427]: Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
2014-10-08T10:05:03+13:00 server-here-1 user.info<14> ruby[1427]: Accepts: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
2014-10-08T10:05:04+13:00 server-here-1 user.info<14> ruby[1427]: Rendered unit_balance/index.html.erb within layouts/customer (292.2ms)
2014-10-08T10:05:04+13:00 server-here-1 user.info<14> ruby[1427]: Completed 200 OK in 902ms (Views: 299.6ms | ActiveRecord: 156.7ms)
2014-10-08T10:05:04+13:00 server-here-1 user.info<14> ruby[1427]: Maximum RSS stayed at 282Mb (+0Mb) serving "/unit_balance"
```

**Comment by wvanbergen** [comment]
So what I think is going on is this:
- You don't specify a file format
- Request-log-analyzer tries to find the best matching file format by trying all of the ones it knows about.
- Some file formats use `eval` (this should be fixed) to extract values from the log files.
- Somewhere in your log file, you have the string `"4.27".to_d`, and rla tries to eval that string, causing the errors.

What might fix it for you:
- Specifying a file format on the command line.

What can be fixed in r.l.a.:
- short-term: rescue when calling `eval`
- long-term: don't use `eval`

/cc @barttenbrinke

**Comment by wvanbergen** [comment]
This is the code that causes the issue. As you can see I am currently only handling syntax errors: https://github.com/wvanbergen/request-log-analyzer/blob/master/lib/request_log_analyzer/request.rb#L39-L44

**Comment by willbryant** [comment]
Right, eval would be dangerous, yeah.  Hope there's no `rm -rf /` in our logs!

Thanks for your help, I'll try fixing the format.

**Comment by wvanbergen** [comment]
Can you try the latest master version?
