### ISSUE TITLE
sqlite exception

### ISSUE THREAD

**Issue by matzke** [wvanbergen/request-log-analyzer#49]
hey :-)

sometimes i get the following error, when parsing large log files (about 7-24 MB). sometimes means i cannot reproduce the error, but it seems to occur when doing things in parallel ...

```
    C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:188:in `log': SQLite3::SQLException: SQL logic error or missing database: INSERT INTO "requests" ("first_lineno", "last_lineno") VALUES(53906, 53910) (ActiveRecord::StatementInvalid) 
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/sqlite_adapter.rb:132:in `execute'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/sqlite_adapter.rb:372:in `catch_schema_changes'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/sqlite_adapter.rb:132:in `execute'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:171:in `insert_sql'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/sqlite_adapter.rb:146:in `insert_sql'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:44:in `insert_without_query_dirty'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:18:in `insert'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:2733:in `create_without_callbacks'  ... 27 levels...
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/request-log-analyzer-1.6.4/bin/../lib/request_log_analyzer/controller.rb:320:in `run!'
    from C:/Data/tools/InstantRails/ruby/lib/ruby/gems/1.8/gems/request-log-analyzer-1.6.4/bin/request-log-analyzer:120
    from C:/Data/tools/InstantRails/ruby/bin/request-log-analyzer:19:in `load'
    from C:/Data/tools/InstantRails/ruby/bin/request-log-analyzer:19
```

(i working on a windows system, with instantrails, ruby 1.8.6 and rails 2.2.2, sqlite-ruby 1.2.1 and sqlite version 3.5.4)

thank you

**Comment by barttenbrinke** [comment]
Are you using the sqlite database for something else as well?  This seems to be a sqlite3 issue.

**Comment by matzke** [comment]
Hey, i am using sqlite just for r-l-a. the application itself is using mysql, but when i import the data from the logfiles the application is not running.

i guess it is a sqlite3 issue, too.

thank u

**Comment by wvanbergen** [comment]
It seems like the database file you supplied is corrupt, which is probably an issue because of running the application in parallel. In general, you should not use insert into a SQLite database concurrently. try another RDBMS to insert the request info into, like MySQL.
